### ISSUE TITLE
Typo fix?

### ISSUE THREAD

**Issue by MysteryAngle** [legends2k/2d-transforms-101#1]
<img width="1023" alt="image" src="https://github.com/legends2k/2d-transforms-101/assets/2690494/0cb56ed6-f56d-4f92-a803-053ba6bffbac">

I'm really beginner for learning these concepts, but the Translation might be: P' = (X + tx, `Y` + ty) ?

Thanks for job, good tutorial.

**Comment by legends2k** [comment]
Fixed, thanks for reporting it :)
